Entrega TP2
NicolasTobiasAlmaraz/sensor_temperatura_ambiente pull request #1
Opened 2024-07-22 15:35 UTC by NicolasTobiasAlmaraz

Adjunto los códigos fuente del TP2.
Saludos!

2024-07-24 00:42 UTC, alutenberg requested changes
Me gusta en general el trabajo que hiciste, felicitaciones. Te dejé nomás algunos comentarios.

2024-07-24 00:42 UTC, alutenberg commented on sources/main.cpp
> +* Curso Sistemas Embebidos - TP2
Sugiero que todo esto que está acá lo pases al Readme. No sé qué opina @scaprile , pero yo al menos veo como que es demasiada explicación acá, que quizás en el Readme la podrías poner con formato tal que resulte de lectura más agradable y cómoda.

2024-07-24 00:42 UTC, alutenberg commented on sources/main.cpp
> +    mainControllerApi_init();
No me queda claro de dónde sale este nombre "mainControllerApi". Ojo, está claro que es una cuestión de gusto nomás, pero no deja de llamarme la atención cómo fue que elegiste este nombre en particular.

2024-07-24 00:42 UTC, alutenberg commented on sources/my_app/display/i2clcd.cpp
> +#define COLUMS 20
COLUMNS

2024-07-24 00:42 UTC, alutenberg commented on sources/my_app/display/i2clcd.cpp
> +	data_u = (cmd & 0xf0);
Creo que sería bueno que en algún lugar, acá mismo o en el Readme, expliques un poco qué es todo esto que figura acá, lo mismo en otras funciones de i2clcd.cpp que no tienen ningún tipo de comentario.

2024-07-24 00:42 UTC, alutenberg commented on sources/my_app/display/i2clcd.cpp
> +	// 4 bit initialisation
Fijate que esta función sí que está mucho más "explicada" que las funciones anteriores.

2024-07-24 00:42 UTC, alutenberg commented on sources/my_app/display/i2clcd.cpp
> +void lcd_send_string(const char *str)
Acá de nuevo, fijate que hay un montón de cosas "mágicas" que no hay forma de saber qué son, porque no hay ni un comentario.

2024-07-24 00:42 UTC, alutenberg commented on sources/my_app/display/i2clcd.cpp
> +	for (int i = 0; i < (COLUMS - column); i++)
Acá también tenes "COLUMS"

2024-07-24 00:42 UTC, alutenberg commented on sources/my_app/led/myapp_led.cpp
> +/**
Acá tengo dos dudas:
1) ¿Por qué decidiste usar una función para encender el LED y otra función para apagar el LED? ¿Por que no una única función que con un parámetro indiques si querés encender o apagar el LED?
2) ¿Por qué elegiste usar la palabra "prender" en el nombre de la función si incluso en tu comentario usas "Enciende"?

2024-07-24 03:25 UTC, NicolasTobiasAlmaraz commented on sources/main.cpp
> +* Curso Sistemas Embebidos - TP2
Dale, me parece bien agregarlo en el readme.
Eso lo puse ahi porque generé la documentación con Doxygen y ahí se visualiza todo más lindo en el HTML que en el codigo.
Y ahora que me lo decís, la documentacion me quedó fuera del pull request también.

Tanto el readme como la documentacion que quedaron en el branch main🤦‍♂️

2024-07-24 03:43 UTC, NicolasTobiasAlmaraz commented on sources/main.cpp
> +    mainControllerApi_init();
Concuerdo, en este caso sería mucho mejor llamarlo "app_init() y app_loop()".

La explicación de los nombres es media rebuscada. Me acostumbré a siempre llamarlo así porque casi siempre que hago una app programo un "main controller" y un "external controller"
- "main controller": la api de más alto nivel que gobierna todo el sistema embebido
- "external controller": sería una especie de interfaz con el mundo exterior (por ejemplo con una UART o algo por el estilo).

Entonces, para testear el sistema / detectar alguna falla / etc. Hago uso de este external controller que permite "apagar al main" y adueñarse de todas las APIs de más bajo nivel y recursos de hw. Entonces de esa manera desde una PC puedo leer sensores, generar plots, probar otras maquinas de estados sobre el mismo hardware, etc.

Esto del "external controller" no lo hice para el tp pero esa es la explicación de por qué me acostumbré a usar ese nombre raro jaja. Me acostumbré a decirle "main controller" al programa principal que corre dentro del uC y "external controller" a la interfaz X que permite usar una maq de estados que corre fuera del sistema embebido pero usa los recursos de hw de la placa.

2024-07-24 03:48 UTC, NicolasTobiasAlmaraz commented on sources/my_app/display/i2clcd.cpp
> +#define COLUMS 20
Esa parte quedó en el readme. Perdón que me faltó subirlo. Lo que pasó fue que usé APIs de otros autores.

Los drivers del sensor DHT22 y del display LCD los saqué de internet. Los autores están citados en la parte de "authors" en sus apis. Tal vez sería bueno que ponga en el readme también los links a los repos de su trabajo.

- La API del display estaba hecha para STM32 usando la HAL oficial de ST. Yo solamente modifiqué las partes donde usa estas funciones de la HAL para usar las funciones de mbed.h que vimos en clase. Esto lo aclaré en i2clcd.h:
```
/**
* @file           : i2clcd.h
* @brief          : Library for I2C LCD display with mbedOS
* @author controllerstech, 2019-05-29
* https://controllerstech.com/lcd-20x4-using-i2c-with-stm32/
*
* @author (modified) Nicolas Almaraz, 2024-07-21
*
* Note Nicolas Almaraz:
* I have adapted this API for use within the mbed framework
*/
```
- La API del DHT22 estaba hecha para mbed directamente asi que hice un copy paste de los archivos (la cabecera /***/, comentarios, etc, son del autor original).

Si les parece puedo documentar con mis palabras el trabajo de estas personas

2024-07-24 03:52 UTC, NicolasTobiasAlmaraz commented on sources/my_app/led/myapp_led.cpp
> +/**
1- Lo pensé pero como que el led es anodo común me quedaba raro encenderlo poniendo "setLed(false)" (aunque ahora que lo pienso podría negarlo adentro y problema resuelto)
2- La verdad que no sé. Tenés razón, sería más claro usar "ledApi_encenderLedX()"

Esta parte si te parece la modifico para que quede más prolija

2024-07-24 11:57 UTC, alutenberg commented on sources/main.cpp
> +* Curso Sistemas Embebidos - TP2
Sí, tenes razón que al usar Doxygen es conveniente documentar tal como lo hiciste, dejalo así si querés.
Por otro lado, efectivamente la documentación te quedó afuera, el readme también. Pero los podes incluir ahora en el branch (lo borras del main y los pones en el branch) y los reviso.

2024-07-24 11:58 UTC, alutenberg commented on sources/main.cpp
> +    mainControllerApi_init();
Ok! Entonces es cuestión de aclarar estas cosas, para que la persona que lea el código pueda entender todo esto, que está muy bien, pero es imposible de saber sin esta explicación tuya.

2024-07-24 11:59 UTC, alutenberg commented on sources/my_app/display/i2clcd.cpp
> +#define COLUMS 20
Ok! Sí, de acuerdo. Dale. Gracias.
¿Y esas personas escribieron "COLUMS"? ¿Sin N?

2024-07-24 11:59 UTC, alutenberg commented on sources/my_app/display/i2clcd.cpp
> +	data_u = (cmd & 0xf0);
Me parece que este comentario mío te quedó sin responder.

2024-07-24 12:00 UTC, alutenberg commented on sources/my_app/display/i2clcd.cpp
> +void lcd_send_string(const char *str)
Me parece que este comentario mío te quedó sin responder.

2024-07-24 12:00 UTC, alutenberg commented on sources/my_app/display/i2clcd.cpp
> +	for (int i = 0; i < (COLUMS - column); i++)
Por las dudas, este también quedó sin responder.

2024-07-24 12:04 UTC, alutenberg commented on sources/my_app/led/myapp_led.cpp
> +/**
1- Sí, esto como vos prefieras. Lo mío es una sugerencia nomás. Queda en vos decidir hacerlo o no. Solo decime qué decidiste hacer.
2- Sí, este punto me parece que lo podes cambiar sin mucho esfuerzo, de "prender" a "encender"

2024-07-24 13:56 UTC, NicolasTobiasAlmaraz commented on sources/main.cpp
> +* Curso Sistemas Embebidos - TP2
Dale

2024-07-24 14:00 UTC, NicolasTobiasAlmaraz commented on sources/my_app/display/i2clcd.cpp
> +#define COLUMS 20
Sí.
Ya que estoy le agrego la N también

2024-07-24 14:01 UTC, NicolasTobiasAlmaraz commented on sources/my_app/display/i2clcd.cpp
> +	data_u = (cmd & 0xf0);
Me parece bien. Esto es parte del archivo que no escribí yo. Pero le agrego los comentarios

2024-07-24 14:03 UTC, alutenberg commented on sources/my_app/display/i2clcd.cpp
> +	data_u = (cmd & 0xf0);
Ok! Una vez que hagas estos cambios y lo de la N en COLUMS y todo eso acordate de hacer por favor un "re-request review" así sé cuando debo mirar todo esto. Gracias!

2024-07-24 14:04 UTC, NicolasTobiasAlmaraz commented on sources/my_app/display/i2clcd.cpp
> +	// 4 bit initialisation
Perfecto

2024-07-24 14:04 UTC, NicolasTobiasAlmaraz commented on sources/my_app/display/i2clcd.cpp
> +void lcd_send_string(const char *str)
Sí, esto es lo de i2clcd.c que le voy a agregar comentarios

2024-07-24 14:04 UTC, NicolasTobiasAlmaraz commented on sources/my_app/display/i2clcd.cpp
> +	for (int i = 0; i < (COLUMS - column); i++)
Idem comentario anterior.
Igualmente ya que voy a cambiarlo le agrego la N.

2024-07-24 14:04 UTC, NicolasTobiasAlmaraz commented on sources/my_app/led/myapp_led.cpp
> +/**
También lo corrijo

2024-07-24 14:06 UTC, NicolasTobiasAlmaraz commented on sources/main.cpp
> +    mainControllerApi_init();
Tenés razón, mejor le cambio el nombre a esto también

2024-07-24 14:07 UTC, NicolasTobiasAlmaraz commented on sources/my_app/display/i2clcd.cpp
> +	data_u = (cmd & 0xf0);
Dale, muchas gracias Ariel.
Buena semana!

2024-07-24 14:14 UTC, alutenberg commented on sources/my_app/display/i2clcd.cpp
> +	data_u = (cmd & 0xf0);
Por nada! Igualmente. Saludos.

2024-07-24 20:59 UTC, merged

2024-07-27 17:32 UTC, alutenberg commented on sources/main.cpp
> +* Curso Sistemas Embebidos - TP2
Ok, Doy por resuelto este comentario.

2024-07-27 17:36 UTC, alutenberg commented on sources/main.cpp
> +    mainControllerApi_init();
Ok, veo que esto quedó cambiado acá:
- https://github.com/NicolasTobiasAlmaraz/sensor_temperatura_ambiente/blob/entrega_tp2/sources/main.cpp
Doy por resuelto este comentario.

2024-07-27 17:37 UTC, alutenberg commented on sources/my_app/display/i2clcd.cpp
> +#define COLUMS 20
Ok, esto quedó cambiado acá: 
- https://github.com/NicolasTobiasAlmaraz/sensor_temperatura_ambiente/blob/entrega_tp2/sources/my_app/display/i2clcd.cpp
Doy por resuelto este comentario.

2024-07-27 17:37 UTC, alutenberg commented on sources/my_app/display/i2clcd.cpp
> +	data_u = (cmd & 0xf0);
Ya lo cambiaste acá:
- https://github.com/NicolasTobiasAlmaraz/sensor_temperatura_ambiente/blob/entrega_tp2/sources/my_app/display/i2clcd.cpp
Doy por resuelto este comentario.

2024-07-27 17:38 UTC, alutenberg commented on sources/my_app/display/i2clcd.cpp
> +	for (int i = 0; i < (COLUMS - column); i++)
Ok.

2024-07-27 17:38 UTC, alutenberg commented on sources/my_app/display/i2clcd.cpp
> +void lcd_send_string(const char *str)
Ok, perfecto. Doy por resuelto este comentario.

2024-07-27 17:39 UTC, alutenberg commented on sources/my_app/led/myapp_led.cpp
> +/**
PErfecto:
- https://github.com/NicolasTobiasAlmaraz/sensor_temperatura_ambiente/blob/entrega_tp2/sources/my_app/led/myapp_led.cpp
Doy por resuelto este comentario.

2024-07-27 17:40 UTC, alutenberg reviewed
Están muy bien todos los cambios que hiciste, queda aprobado.