Re - Entrega tp2
NicolasTobiasAlmaraz/sensor_temperatura_ambiente pull request #2
Opened 2024-07-26 13:50 UTC by NicolasTobiasAlmaraz

Reentrgea TP2:
- Agregar readme y documentacion doxygen al pull request
- Cambiar nombre mainControllerApi
- Cambiar "encenderLed y apagarLed" por "setLed(bool state)"
- Documentar mejor las Apis i2clcd y DHT (que son de otros autores)
- En el readme agregar los links a los repositorios i2clcd y DHT originales de los autores

2024-07-26 14:18 UTC, scaprile requested changes

2024-07-26 14:18 UTC, scaprile commented on README.md
Fijate que Github te está diciendo que hay conflictos que no puede resolver de forma automática y que no puede integrar este archivo al tronco principal.
O sea: hay cambios acá que parten de una versión anterior en el main y que chocan con cambios de una versión posterior en el main. Tenés que hacer:
- `git rebase main`, seguramente va a indicarte una falla y cómo seguir. Si pasa: pasa, listo, push.
- resolver esos conflictos manualmente eligiendo qué se queda en este PR y qué no,
- marcar el conflicto como solucionado: `git add README.md`
- continuar el rebase: `git rebase --continue` (pero hacele caso a lo que te diga git porque puedo recordar mal)
- push: `git push -f origin entrega_tp2`. El `-f` es para forzar, porque el rebase reordena los commits

@alutenberg @EFilomena : FYI

2024-07-26 17:35 UTC, NicolasTobiasAlmaraz commented on README.md
Perfecto, ahi lo reviso
Gracias!

2024-07-26 17:51 UTC, NicolasTobiasAlmaraz commented on README.md
Ejecute:
git rebase main
- Me tira q hay un montón de conflictos en los archivos que genera Doxygen de la documentación
- Y hay conflictos también en el readme

Después de tirarme todos los conflictos me dice esto:
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 59e2c20... Actualizo archivos para segunda entrega

Entiendo que los conflictos nacen xq temporalmente hice esto:
1- Cargo a main doc y readme
2- Hago un nuevo branch "entrega_tp2" donde añado codigo
3- Elimino de main la doc y readme
4- Modifico en "entrega_tp2" todos los archivos (sources, doc y readme)

Ahora que quiero mergear debería elegir que sobrevivan los archivos del branch tp2 y que ignore todo lo que estaba en main.

No me queda muy claro como proceder para hacer eso.
Manualmente como tengo que hacer para decirle que se quede con todo lo que está en el branch "entrega_tp2"??

2024-07-26 22:58 UTC, scaprile commented on README.md
Lo que genera los conflictos es lo que te expliqué más arriba.
Eso sucede porque empezás mal.
No agregues nada a main, empezá desde el branch, nunca dijimos "ponga cosas en main y después sáquelas"
La forma de arreglarlo es exactamente igual a lo que te pasó días atrás: volvés el main al punto de branch, entonces cuando hagas merge vas a sobreescribir main con todo lo del branch del TP.
Sí, te quedan los docs en main, porque si los sacás el pobre git se vuelve loco preguntándose: "este tipo me pide unir algo con cosas que ya no están más, a quién le hago caso, al commit que pone o al commit que saca ?" pero en vez de entrar en pánico te tira la pelota a vos y te dice "hacete cargo"

2024-07-26 23:36 UTC, NicolasTobiasAlmaraz commented on README.md
Ahh okey!

Perdón, estaba entendiendo mal.
Claro, naturalmente generé conflictos en todos los archivos subidos al main.

Ahora sí está todo más claro.
Lo vuelvo a subir y les aviso.
Muchas gracias Sergio.

2024-07-27 00:11 UTC, alutenberg commented on README.md
@NicolasTobiasAlmaraz
En función de lo que venís conversando con @scaprile voy a esperar a que termines de acomodar todo esto que comentas y una vez que lo hayas hecho y has un re-request review revisaré tu pull request, ok?
Quedo atento,
Saludos,
Ariel.

2024-07-27 00:29 UTC, NicolasTobiasAlmaraz commented on README.md
Hola Ariel, como andas?
Ya está listo para ser corregido.
Hace unos minutos generé el re-request.

Lo único que quedó diferente a lo que me habías pedido originalmente sería que no pude "borrar los archivos del branch main y añadirlos al branch entrega_tp2" porque eso genera conflictos cuando hago el pull request (y eran demasiados como para corregirlos manualmente).

La solución que tomé fue hacer lo que me recomendó Sergio: 
Volver al punto donde generé el branch y pisar los archivos viejos que quedaron en main.

Espero sus correcciones
Nos vemos mañana, saludos!

2024-07-27 17:41 UTC, alutenberg approved these changes
Están muy bien los cambios que hiciste, queda aprobado.

2024-07-27 17:41 UTC, alutenberg commented on README.md
Perfecto, ahí lo revisé. Queda aprobado. Felicitaciones!

2024-07-28 21:07 UTC, NicolasTobiasAlmaraz commented on README.md
@alutenberg Genial, muchas gracias!
@scaprile Avisame si te quedaba pendiente revisar algo en particular, sino ya hago el merge

Muchas gracias a los dos. Saludos!

2024-07-29 02:37 UTC, scaprile approved these changes

2024-07-29 02:49 UTC, merged